FB_APP_ID: ""
FB_APP_SECRET: ""
FB_APP_NAMESPACE: ""
S3_BUCKET: ""
S3_ACCESS_KEY_ID: ""
S3_SECRET_ACCESS_KEY: ""
SENDGRID_PASSWORD: aizj8zom9413
SENDGRID_USERNAME: app85902413@heroku.com
DOMAIN: localhost
